#include "text_processing.hpp"

#include <algorithm>
#include <cctype>
#include <functional>
#include <regex>
#include <sstream>
#include <stdexcept>

namespace text_processing
{
    namespace
    {
        std::vector<std::string> splitUtf8(const std::string& text)
        {
            std::vector<std::string> result;
            for (size_t i = 0; i < text.size();)
            {
                const auto byte = static_cast<unsigned char>(text[i]);
                size_t length = 1;
                if ((byte & 0xE0) == 0xC0)
                {
                    length = 2;
                }
                else if ((byte & 0xF0) == 0xE0)
                {
                    length = 3;
                }
                else if ((byte & 0xF8) == 0xF0)
                {
                    length = 4;
                }

                if (i + length > text.size())
                {
                    length = 1;
                }
                result.push_back(text.substr(i, length));
                i += length;
            }
            return result;
        }

        void appendUtf8Symbols(std::vector<std::string>& result, const std::string& text)
        {
            for (const auto& symbol : splitUtf8(text))
            {
                result.push_back(symbol);
            }
        }

        std::vector<std::string> buildSymbols()
        {
            std::vector<std::string> result;
            result.push_back("_");

            appendUtf8Symbols(
                result,
                ";:,.!?"
                "\xC2\xA1\xC2\xBF"
                "\xE2\x80\x94\xE2\x80\xA6"
                "\""
                "\xC2\xAB\xC2\xBB"
                "\xE2\x80\x9C\xE2\x80\x9D"
                " ");
            appendUtf8Symbols(
                result,
                "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz");

            // TODO: Python VITS appends a large IPA symbol table here. Add it
            // with generated byte escapes when the phonemizer path is wired in.
            return result;
        }

        std::string replaceAll(std::string text, const std::string& from, const std::string& to)
        {
            size_t pos = 0;
            while ((pos = text.find(from, pos)) != std::string::npos)
            {
                text.replace(pos, from.size(), to);
                pos += to.size();
            }
            return text;
        }

        std::string fallbackPhonemizeEnglish(const std::string& text)
        {
            // Python VITS calls phonemizer/espeak here. Keep this as a small
            // compatibility hook until an espeak-backed phonemizer is wired in.
            return text;
        }

        const std::vector<std::string>& smallNumbers()
        {
            static const std::vector<std::string> value = {
                "zero",
                "one",
                "two",
                "three",
                "four",
                "five",
                "six",
                "seven",
                "eight",
                "nine",
                "ten",
                "eleven",
                "twelve",
                "thirteen",
                "fourteen",
                "fifteen",
                "sixteen",
                "seventeen",
                "eighteen",
                "nineteen"};
            return value;
        }

        const std::vector<std::string>& tensNumbers()
        {
            static const std::vector<std::string> value = {
                "",
                "",
                "twenty",
                "thirty",
                "forty",
                "fifty",
                "sixty",
                "seventy",
                "eighty",
                "ninety"};
            return value;
        }

        std::string joinWords(const std::vector<std::string>& words)
        {
            std::ostringstream stream;
            for (size_t i = 0; i < words.size(); ++i)
            {
                if (i != 0)
                {
                    stream << ' ';
                }
                stream << words[i];
            }
            return stream.str();
        }

        std::string numberToWords(int64_t number)
        {
            if (number < 0)
            {
                return "minus " + numberToWords(-number);
            }
            if (number < 20)
            {
                return smallNumbers()[static_cast<size_t>(number)];
            }
            if (number < 100)
            {
                const auto tens = number / 10;
                const auto remainder = number % 10;
                if (remainder == 0)
                {
                    return tensNumbers()[static_cast<size_t>(tens)];
                }
                return tensNumbers()[static_cast<size_t>(tens)] + " " + smallNumbers()[static_cast<size_t>(remainder)];
            }
            if (number < 1000)
            {
                const auto hundreds = number / 100;
                const auto remainder = number % 100;
                if (remainder == 0)
                {
                    return smallNumbers()[static_cast<size_t>(hundreds)] + " hundred";
                }
                return smallNumbers()[static_cast<size_t>(hundreds)] + " hundred " + numberToWords(remainder);
            }

            const std::vector<std::pair<int64_t, std::string>> scales = {
                {1000000000LL, "billion"},
                {1000000LL, "million"},
                {1000LL, "thousand"}};
            for (const auto& scale : scales)
            {
                if (number >= scale.first)
                {
                    const auto major = number / scale.first;
                    const auto remainder = number % scale.first;
                    auto result = numberToWords(major) + " " + scale.second;
                    if (remainder != 0)
                    {
                        result += " " + numberToWords(remainder);
                    }
                    return result;
                }
            }

            return "";
        }

        std::string ordinalToWords(int64_t number)
        {
            static const std::unordered_map<int64_t, std::string> irregular = {
                {0, "zeroth"},
                {1, "first"},
                {2, "second"},
                {3, "third"},
                {4, "fourth"},
                {5, "fifth"},
                {6, "sixth"},
                {7, "seventh"},
                {8, "eighth"},
                {9, "ninth"},
                {10, "tenth"},
                {11, "eleventh"},
                {12, "twelfth"},
                {13, "thirteenth"},
                {14, "fourteenth"},
                {15, "fifteenth"},
                {16, "sixteenth"},
                {17, "seventeenth"},
                {18, "eighteenth"},
                {19, "nineteenth"}};

            const auto found = irregular.find(number);
            if (found != irregular.end())
            {
                return found->second;
            }
            if (number < 100 && number % 10 == 0)
            {
                auto base = tensNumbers()[static_cast<size_t>(number / 10)];
                if (base.size() >= 1 && base.back() == 'y')
                {
                    base.pop_back();
                    base += "ieth";
                }
                return base;
            }

            const auto base = numberToWords(number);
            const auto lastSpace = base.find_last_of(' ');
            if (lastSpace == std::string::npos)
            {
                return base + "th";
            }

            const auto prefix = base.substr(0, lastSpace + 1);
            const auto lastWord = base.substr(lastSpace + 1);
            for (int64_t i = 0; i < 100; ++i)
            {
                if (numberToWords(i) == lastWord)
                {
                    return prefix + ordinalToWords(i);
                }
            }
            return base + "th";
        }

        std::string removeCommasFromNumbers(const std::string& text)
        {
            static const std::regex commaNumberRe("([0-9][0-9,]+[0-9])");
            std::string result;
            std::sregex_iterator current(text.begin(), text.end(), commaNumberRe);
            std::sregex_iterator end;
            size_t last = 0;
            for (; current != end; ++current)
            {
                const auto match = *current;
                result.append(text, last, static_cast<size_t>(match.position()) - last);
                auto number = match.str(1);
                number.erase(std::remove(number.begin(), number.end(), ','), number.end());
                result += number;
                last = static_cast<size_t>(match.position() + match.length());
            }
            result.append(text, last, std::string::npos);
            return result;
        }

        std::string expandDollarAmount(const std::smatch& match)
        {
            const auto amount = match.str(1);
            const auto dot = amount.find('.');
            if (dot != std::string::npos && amount.find('.', dot + 1) != std::string::npos)
            {
                return amount + " dollars";
            }

            const auto dollarsPart = dot == std::string::npos ? amount : amount.substr(0, dot);
            const auto centsPart = dot == std::string::npos ? std::string() : amount.substr(dot + 1);
            const auto dollars = dollarsPart.empty() ? 0 : std::stoll(dollarsPart);
            const auto cents = centsPart.empty() ? 0 : std::stoll(centsPart);

            std::vector<std::string> words;
            if (dollars != 0)
            {
                words.push_back(numberToWords(dollars));
                words.push_back(dollars == 1 ? "dollar" : "dollars");
            }
            if (cents != 0)
            {
                words.push_back(numberToWords(cents));
                words.push_back(cents == 1 ? "cent" : "cents");
            }
            if (words.empty())
            {
                return "zero dollars";
            }
            return joinWords(words);
        }

        std::string replaceRegex(
            const std::string& text,
            const std::regex& pattern,
            const std::function<std::string(const std::smatch&)>& replacement)
        {
            std::string result;
            std::sregex_iterator current(text.begin(), text.end(), pattern);
            std::sregex_iterator end;
            size_t last = 0;
            for (; current != end; ++current)
            {
                const auto match = *current;
                result.append(text, last, static_cast<size_t>(match.position()) - last);
                result += replacement(match);
                last = static_cast<size_t>(match.position() + match.length());
            }
            result.append(text, last, std::string::npos);
            return result;
        }

        struct Abbreviation
        {
            std::regex pattern;
            std::string replacement;
        };

        const std::vector<Abbreviation>& abbreviations()
        {
            static const std::vector<Abbreviation> value = {
                {std::regex("\\bmrs\\.", std::regex_constants::icase), "misess"},
                {std::regex("\\bmr\\.", std::regex_constants::icase), "mister"},
                {std::regex("\\bdr\\.", std::regex_constants::icase), "doctor"},
                {std::regex("\\bst\\.", std::regex_constants::icase), "saint"},
                {std::regex("\\bco\\.", std::regex_constants::icase), "company"},
                {std::regex("\\bjr\\.", std::regex_constants::icase), "junior"},
                {std::regex("\\bmaj\\.", std::regex_constants::icase), "major"},
                {std::regex("\\bgen\\.", std::regex_constants::icase), "general"},
                {std::regex("\\bdrs\\.", std::regex_constants::icase), "doctors"},
                {std::regex("\\brev\\.", std::regex_constants::icase), "reverend"},
                {std::regex("\\blt\\.", std::regex_constants::icase), "lieutenant"},
                {std::regex("\\bhon\\.", std::regex_constants::icase), "honorable"},
                {std::regex("\\bsgt\\.", std::regex_constants::icase), "sergeant"},
                {std::regex("\\bcapt\\.", std::regex_constants::icase), "captain"},
                {std::regex("\\besq\\.", std::regex_constants::icase), "esquire"},
                {std::regex("\\bltd\\.", std::regex_constants::icase), "limited"},
                {std::regex("\\bcol\\.", std::regex_constants::icase), "colonel"},
                {std::regex("\\bft\\.", std::regex_constants::icase), "fort"}};
            return value;
        }

        const std::unordered_map<std::string, int64_t>& symbolToId()
        {
            static const std::unordered_map<std::string, int64_t> mapping = [] {
                std::unordered_map<std::string, int64_t> result;
                const auto& syms = symbols();
                for (size_t i = 0; i < syms.size(); ++i)
                {
                    result.emplace(syms[i], static_cast<int64_t>(i));
                }
                return result;
            }();
            return mapping;
        }
    }

    const std::vector<std::string>& symbols()
    {
        static const std::vector<std::string> value = buildSymbols();
        return value;
    }

    int64_t spaceId()
    {
        return symbolToId().at(" ");
    }

    std::string collapseWhitespace(const std::string& text)
    {
        std::string result;
        bool previousWasSpace = false;
        for (const unsigned char ch : text)
        {
            if (std::isspace(ch))
            {
                if (!previousWasSpace)
                {
                    result.push_back(' ');
                }
                previousWasSpace = true;
            }
            else
            {
                result.push_back(static_cast<char>(ch));
                previousWasSpace = false;
            }
        }
        return result;
    }

    std::string lowercase(const std::string& text)
    {
        std::string result;
        result.reserve(text.size());
        for (const unsigned char ch : text)
        {
            result.push_back(static_cast<char>(std::tolower(ch)));
        }
        return result;
    }

    std::string basicCleaners(const std::string& text)
    {
        return collapseWhitespace(lowercase(text));
    }

    std::string convertToAscii(const std::string& text)
    {
        auto result = text;
        result = replaceAll(result, "\xE2\x80\x94", "-");
        result = replaceAll(result, "\xE2\x80\x93", "-");
        result = replaceAll(result, "\xE2\x80\xA6", "...");
        result = replaceAll(result, "\xE2\x80\x9C", "\"");
        result = replaceAll(result, "\xE2\x80\x9D", "\"");
        result = replaceAll(result, "\xE2\x80\x98", "'");
        result = replaceAll(result, "\xE2\x80\x99", "'");
        result = replaceAll(result, "\xC2\xAB", "\"");
        result = replaceAll(result, "\xC2\xBB", "\"");
        result = replaceAll(result, "\xC2\xA1", "!");
        result = replaceAll(result, "\xC2\xBF", "?");
        result = replaceAll(result, "\xC3\xA1", "a");
        result = replaceAll(result, "\xC3\xA0", "a");
        result = replaceAll(result, "\xC3\xA4", "a");
        result = replaceAll(result, "\xC3\xA2", "a");
        result = replaceAll(result, "\xC3\xA5", "a");
        result = replaceAll(result, "\xC3\xA9", "e");
        result = replaceAll(result, "\xC3\xA8", "e");
        result = replaceAll(result, "\xC3\xAB", "e");
        result = replaceAll(result, "\xC3\xAA", "e");
        result = replaceAll(result, "\xC3\xAD", "i");
        result = replaceAll(result, "\xC3\xAC", "i");
        result = replaceAll(result, "\xC3\xAF", "i");
        result = replaceAll(result, "\xC3\xAE", "i");
        result = replaceAll(result, "\xC3\xB3", "o");
        result = replaceAll(result, "\xC3\xB2", "o");
        result = replaceAll(result, "\xC3\xB6", "o");
        result = replaceAll(result, "\xC3\xB4", "o");
        result = replaceAll(result, "\xC3\xBA", "u");
        result = replaceAll(result, "\xC3\xB9", "u");
        result = replaceAll(result, "\xC3\xBC", "u");
        result = replaceAll(result, "\xC3\xBB", "u");
        result = replaceAll(result, "\xC3\xB1", "n");
        result = replaceAll(result, "\xC3\xA7", "c");
        result = replaceAll(result, "\xC3\x9F", "ss");
        return result;
    }

    std::string expandAbbreviations(const std::string& text)
    {
        auto result = text;
        for (const auto& abbreviation : abbreviations())
        {
            result = std::regex_replace(result, abbreviation.pattern, abbreviation.replacement);
        }
        return result;
    }

    std::string normalizeNumbers(const std::string& text)
    {
        auto result = removeCommasFromNumbers(text);

        static const std::regex poundsRe("\xC2\xA3([0-9,]*[0-9]+)");
        result = replaceRegex(
            result,
            poundsRe,
            [](const std::smatch& match) {
                return numberToWords(std::stoll(match.str(1))) + " pounds";
            });

        static const std::regex dollarsRe("\\$([0-9.,]*[0-9]+)");
        result = replaceRegex(result, dollarsRe, expandDollarAmount);

        static const std::regex decimalNumberRe("([0-9]+)\\.([0-9]+)");
        result = replaceRegex(
            result,
            decimalNumberRe,
            [](const std::smatch& match) {
                return numberToWords(std::stoll(match.str(1))) + " point " + numberToWords(std::stoll(match.str(2)));
            });

        static const std::regex ordinalRe("([0-9]+)(st|nd|rd|th)");
        result = replaceRegex(
            result,
            ordinalRe,
            [](const std::smatch& match) {
                return ordinalToWords(std::stoll(match.str(1)));
            });

        static const std::regex numberRe("[0-9]+");
        result = replaceRegex(
            result,
            numberRe,
            [](const std::smatch& match) {
                const auto number = std::stoll(match.str(0));
                if (number > 2000 && number < 2010)
                {
                    return std::string("two thousand ") + numberToWords(number % 100);
                }
                if (number > 1000 && number < 3000 && number % 100 == 0)
                {
                    return numberToWords(number / 100) + " hundred";
                }
                return numberToWords(number);
            });

        return result;
    }

    std::string expandNumbers(const std::string& text)
    {
        return normalizeNumbers(text);
    }

    std::string transliterationCleaners(const std::string& text)
    {
        return collapseWhitespace(lowercase(convertToAscii(text)));
    }

    std::string englishCleaners(const std::string& text)
    {
        auto result = convertToAscii(text);
        result = lowercase(result);
        result = expandNumbers(result);
        result = expandAbbreviations(result);
        result = fallbackPhonemizeEnglish(result);
        return collapseWhitespace(result);
    }

    std::string englishCleaners2(const std::string& text)
    {
        auto result = convertToAscii(text);
        result = lowercase(result);
        result = expandNumbers(result);
        result = expandAbbreviations(result);
        result = fallbackPhonemizeEnglish(result);
        return collapseWhitespace(result);
    }

    std::string cleanText(
        const std::string& text,
        const std::vector<std::string>& cleanerNames)
    {
        auto result = text;
        for (const auto& name : cleanerNames)
        {
            if (name == "basic_cleaners")
            {
                result = basicCleaners(result);
            }
            else if (name == "transliteration_cleaners")
            {
                result = transliterationCleaners(result);
            }
            else if (name == "english_cleaners")
            {
                result = englishCleaners(result);
            }
            else if (name == "english_cleaners2")
            {
                result = englishCleaners2(result);
            }
            else
            {
                throw std::invalid_argument("Unknown cleaner: " + name);
            }
        }
        return result;
    }

    std::vector<int64_t> cleanedTextToSequence(const std::string& cleanedText)
    {
        std::vector<int64_t> result;
        const auto& mapping = symbolToId();
        for (const auto& symbol : splitUtf8(cleanedText))
        {
            auto found = mapping.find(symbol);
            if (found != mapping.end())
            {
                result.push_back(found->second);
            }
        }
        return result;
    }

    std::vector<int64_t> textToSequence(
        const std::string& text,
        const std::vector<std::string>& cleanerNames)
    {
        return cleanedTextToSequence(cleanText(text, cleanerNames));
    }

    std::string sequenceToText(const std::vector<int64_t>& sequence)
    {
        std::string result;
        const auto& syms = symbols();
        for (const auto id : sequence)
        {
            if (id < 0 || static_cast<size_t>(id) >= syms.size())
            {
                throw std::out_of_range("sequenceToText received an invalid symbol id.");
            }
            result += syms[static_cast<size_t>(id)];
        }
        return result;
    }
}
